AWSTemplateFormatVersion: 2010-09-09
Description: |
  flask uygulaması ile cloudformationdan instance ayaga kaldırmak.
Parameters:
  LatestAmiId:
      Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
      Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64'
  KeyName:
    Description: Choose your key pair
    Type: AWS::EC2::KeyPair::KeyName
Resources:
  MySecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and HTTP # Required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebServerHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref MySecGrp
      Tags:
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName}

      UserData: !Base64 |
        #!/bin/bash
         yum update -y
         yum install python3 -y
         FOLDER="https://raw.githubusercontent.com/FS-MEHMET/001-roman-numerals-converter/main"
         cd /home/ec2-user
         python3 -m venv env
         source env/bin/activate
         wget ${FOLDER}/roman-numerals-converter-app.py
         mkdir templates && cd templates
         wget ${FOLDER}/templates/index.html
         wget ${FOLDER}/templates/result.html
         cd ..
         pip install flask
         python3 roman-numerals-converter-app.py

Outputs:
  DnsName:
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt WebServerHost.PublicDnsName

      
